// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package openapi

const (
	ApiKeyScopes = "apiKey.Scopes"
	BearerScopes = "bearer.Scopes"
)

// AdminUser defines model for AdminUser.
type AdminUser struct {
	Email string `json:"email"`
	Id    int    `json:"id"`
	Name  string `json:"name"`
}

// AdminUserCreateResponse defines model for AdminUserCreateResponse.
type AdminUserCreateResponse struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// AdminUserResponse defines model for AdminUserResponse.
type AdminUserResponse struct {
	AdminUsers *AdminUsers `json:"adminUsers,omitempty"`
	Total      int         `json:"total"`
}

// AdminUserSignInResponse defines model for AdminUserSignInResponse.
type AdminUserSignInResponse struct {
	AccessToken  string     `json:"access-token"`
	Id           string     `json:"id"`
	RefreshToken string     `json:"refresh-token"`
	Yourself     *AdminUser `json:"yourself,omitempty"`
}

// AdminUsers defines model for AdminUsers.
type AdminUsers = []AdminUser

// RefreshToken defines model for refreshToken.
type RefreshToken = string

// AdminUserCreateRequest defines model for AdminUserCreateRequest.
type AdminUserCreateRequest struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

// AdminUserSignInRequest defines model for AdminUserSignInRequest.
type AdminUserSignInRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// PostV1AdminsJSONBody defines parameters for PostV1Admins.
type PostV1AdminsJSONBody struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

// PostV1AdminUserAccessTokenParams defines parameters for PostV1AdminUserAccessToken.
type PostV1AdminUserAccessTokenParams struct {
	// RefreshToken Refresh token
	RefreshToken RefreshToken `form:"refreshToken" json:"refreshToken"`
}

// PostV1AdminUserSignInJSONBody defines parameters for PostV1AdminUserSignIn.
type PostV1AdminUserSignInJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// PostV1AdminUserSignInMultipartBody defines parameters for PostV1AdminUserSignIn.
type PostV1AdminUserSignInMultipartBody = map[string]interface{}

// PostV1AdminsJSONRequestBody defines body for PostV1Admins for application/json ContentType.
type PostV1AdminsJSONRequestBody PostV1AdminsJSONBody

// PostV1AdminUserSignInJSONRequestBody defines body for PostV1AdminUserSignIn for application/json ContentType.
type PostV1AdminUserSignInJSONRequestBody PostV1AdminUserSignInJSONBody

// PostV1AdminUserSignInMultipartRequestBody defines body for PostV1AdminUserSignIn for multipart/form-data ContentType.
type PostV1AdminUserSignInMultipartRequestBody = PostV1AdminUserSignInMultipartBody
